.github/workflows/ci.yml

Addition of a GitHub Action workflow for automated testing on push and pull request git events.
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Manual testing is required.
Issue Number: #13
The GitHub Action will be triggered on push and pull request git events on the repository.
```
[ ] Yes
[x] No
```

chore: 🤖 add GitHub Action for automated testing

---

packages/falso/src/lib/rgb.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor: 💡 Update rgb to use shared getRandomInRange function

---

packages/falso/src/lib/pronoun.json
packages/falso/src/lib/pronoun.ts

- [] Tests for the changes have been added (for bug fixes / features)
Closes #36
```
[ ] Bugfix
[x] Feature
```
No current behaviour
Issue Number: #36
Add pronoun function that returns random pronouns from assorted json list
```
[ ] Yes
[x] No
```
I haven't added tests are it's just using the `rand()` function with a JSON file

feat: add pronouns

---

packages/falso/src/index.ts
packages/falso/src/lib/alpha.ts
packages/falso/src/lib/arn.ts
packages/falso/src/lib/avatar.ts
packages/falso/src/lib/aws-region.json
packages/falso/src/lib/aws-region.ts
packages/falso/src/lib/aws-service.json
packages/falso/src/lib/aws-service.ts
packages/falso/src/lib/between.ts
packages/falso/src/lib/email.ts
packages/falso/src/lib/number.ts
packages/falso/src/lib/password.ts
packages/falso/src/lib/past.ts
packages/falso/src/lib/role.json
packages/falso/src/lib/role.ts
packages/falso/src/lib/semver.ts
packages/falso/src/lib/text.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat:  add randRole and aws

---

packages/falso/src/index.ts
packages/falso/src/lib/random.ts

Export the seed function, fix random function docs
✅ Closes: #46
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: 🐞 export seed function

---

packages/falso/src/tests/seed.spec.ts

```
[x] Bugfix
[ ] Feature
```
At the moment in `seed` test, `seed` function is used to set a custom seed.
This means that other tests that are run after `seed` test will use the same seed value.
After `seed` test, seed value is set again to be nondeterministic
```
[ ] Yes
[x] No
```

test(seed): reset seed after tests are run

---

packages/falso/src/lib/hsl.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: updated example for HSL color

---

packages/falso/src/index.ts
packages/falso/src/lib/product-category.json
packages/falso/src/lib/product-category.ts
packages/falso/src/lib/product.ts
packages/falso/src/tests/product-category.spec.ts
packages/falso/src/tests/product.spec.ts

```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[X] No
```

feat: 🔥 Add random product entity

---

docs/docs/book.md
packages/falso/src/index.ts
packages/falso/src/lib/book.json
packages/falso/src/lib/book.ts
packages/falso/src/tests/book.spec.ts

A new method for getting a random book (a category can also be
specified)
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: 🔥 Add random book

---

packages/falso/src/lib/gender-code.json
packages/falso/src/lib/gender.ts
packages/falso/src/tests/gender.spec.ts

The PR extends the existing randGender method to include abbreviations
```
[ ] Bugfix
[x] Feature
```
Issue Number: #50 
```
[ ] Yes
[x] No
```

feat: extend randGender method to return abbreviated genders #50

---

packages/falso/src/index.ts

Export randPronoun and randQuote functions which fixes text docs page
✅ Closes: #99
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 export randPronoun and randQuote functions

---

packages/falso/src/lib/pronoun.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: 📘 Change randPronoun category to person

---

packages/falso/src/lib/mask.ts
packages/falso/src/tests/mask.spec.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: updated to accept user specified mask

---

packages/falso/src/index.ts
packages/falso/src/lib/status.json
packages/falso/src/lib/status.ts
packages/falso/src/tests/status.spec.ts

✅ Closes #112 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #112 
```
[ ] Yes
[x] No
```

feat: 🔥 added random status generator

---

packages/falso/src/index.ts
packages/falso/src/lib/font-size.ts
packages/falso/src/tests/font-size.spec.ts

- [Χ] The commit message follows our guidelines: https://github.com/ngneat/falso/blob/master/CONTRIBUTING.md#commit
- [Χ] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[Χ] Feature
```
Issue Number: #116 
```
[ ] Yes
[Χ] No
```

feat:  🔥 Add random fontSize

---

README.md
packages/falso/src/index.ts
packages/falso/src/lib/binary.ts
packages/falso/src/tests/binary.spec.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #130 
```
[ ] Yes
[X] No
```

feat:  🔥 Add random binary

---

docs/src/css/custom.css
docs/src/theme/ReactLiveScope/index.js

✅ Closes: #139
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: 📘 Update ReactJson styles to match with doc theme

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Changed "excepts" to "accepts"in CONTRIBUTING.md .
```
[ ] Yes
[x] No
```

style: 💄 typo fix from excepts to accepts

---

README.md

Added relative link to CODE_OF_CONDUCT.md for code of conduct bade in
README.md file
✅ Closes: #163
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Issue Number: #163 
Link fixed.
```
[ ] Yes
[x] No
```

style: 💄 add relative link to CODE_OF_CONDUCT.md in README.md

---

docs/docusaurus.config.js

✅ Closes: #165
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #165 
reset Docs link in Footer to Getting Started section
```
[ ] Yes
[x] No
```

docs: 📘 reset Docs link in Footer to Getting Started section

---

docs-generator.js
docs/src/theme/ReactLiveScope/index.js
packages/falso/src/lib/between-date.ts

Add default value for from & to on randBetweenDate. Update exmple
template to handle dates
✅ Closes: #170
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 Date function examples in docs

---

packages/falso/src/lib/address.ts
packages/falso/src/lib/full-address.ts
packages/falso/src/tests/address.spec.ts
packages/falso/src/tests/full-address.spec.ts

Made county & country optional for address & fullAddres
✅ Closes: #181 
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: 🔥 Address optional county and country

---

README.md
docs/docs/getting-started.mdx
packages/falso/src/index.ts
packages/falso/src/lib/code-snippet.json
packages/falso/src/lib/code-snippet.ts
packages/falso/src/tests/code-snippet.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #129 
Adds randCodeSnippet.
```
[ ] Yes
[x] No
```

feat: 🔥 Add random code snippet

---

packages/falso/src/lib/future-date.ts
packages/falso/src/lib/past-date.ts
packages/falso/src/tests/alpha-numeric.spec.ts
packages/falso/src/tests/between-date.spec.ts
packages/falso/src/tests/future-date.spec.ts
packages/falso/src/tests/past-date.spec.ts

Add tests for randFutureDate, randPastDate, randAlphaNumeric &
randBetweenDate
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[x] No
```

test: 🥳 Add some missing spec files

---

packages/falso/src/lib/country.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
The same with less countries
Add some new countries to the list. 
```
[ ] Yes
[x] No
```

feat: add some countries

---

README.md
docs-generator.js
docs/docs/getting-started.mdx
packages/falso/src/index.ts
packages/falso/src/lib/text-range.ts
packages/falso/src/tests/text-range.spec.ts

Add new funtion & tests. Update docs-generator to handle options
✅ Closes: #185
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: 🔥 Add rand text range function

---

packages/falso/src/tests/food.spec.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 Broken food tests caused by merge

---

.github/workflows/docs.yml

From #177
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```

ci: 😺 Tweak docs to only deploy when package is published

---

packages/falso/src/tests/food.spec.ts

✅ Closes: #187
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 Fix randfood tests

---

packages/falso/src/lib/dog.json
packages/falso/src/lib/football-team.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Working as expected with less dog breeds and football teams
Working as expected with more dog breeds and football teams
```
[ ] Yes
[X] No
```

feat: Added dog breeds and football teams

---

packages/falso/src/lib/food.json
packages/falso/src/lib/food.ts

Added new list of food from chile
```
[ ] Bugfix
[x] Feature
```
South America need more country options 
Another LATAM country in option list
```
[ ] Yes
[x] No
```

feat: 🔥 Add new food from latam

---

packages/falso/src/lib/flight-details.ts
packages/falso/src/tests/flight-details.spec.ts

@NetanelBasal - Sorry, this commit didn't get pushed. This is the one that exposes the interface (It also tweaks them slightly)
✅ Closes: #197
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

refactor: 💡 Tweak flight details entity model and export it

---

packages/falso/src/tests/flight-number.spec.ts

This allows us to add more airlines without tests failing
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 Add test for fall back flight number logic

---

README.md
docs/docs/getting-started.mdx
packages/falso/src/index.ts
packages/falso/src/lib/airport-code.ts
packages/falso/src/lib/airport-name.ts
packages/falso/src/lib/airport.json
packages/falso/src/lib/airport.ts
packages/falso/src/lib/flight-details.ts
packages/falso/src/tests/airport-code.spec.ts
packages/falso/src/tests/airport-name.spec.ts
packages/falso/src/tests/flight-details.spec.ts
packages/falso/src/tests/text-range.spec.ts

Add new functions and update randFlightDetails to use them. Fix sometime
failing test
✅ Closes: #208
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```

feat: 🔥 Add random airport name, code and entity functions

---

packages/falso/src/lib/flight-number.ts
packages/falso/src/tests/text-range.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Refactor flight number

---

packages/falso/src/lib/rand-json.ts

- Object key replaced with uuid()
- Reduce replaced with For loop for better performance
✅ Closes: #180
```
[x] Bugfix
[ ] Feature
```
Issue Number: #180

fix: 🐞 randJSON: prevent key overwritten when looping

---

packages/falso/src/lib/food.json
packages/falso/src/lib/food.ts

```
[ ] Bugfix
[x] Feature
```
Getting food from Ecuador
Add food from Ecuador
```
[ ] Yes
[x] No
```

feat: 🔥 Add food from Ecuador

---

packages/falso/src/lib/food.json
packages/falso/src/lib/food.ts
packages/falso/src/tests/email.spec.ts
packages/falso/src/tests/first-name.spec.ts
packages/falso/src/tests/flight-number.spec.ts
packages/falso/src/tests/food.spec.ts
packages/falso/src/tests/last-name.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

💡 Refactor flakey tests that relied on seed values

---

docs/src/consolePlayground/index.js

Add null check for window
✅ Closes: #225
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 window is not defined

---

docs/src/consolePlayground/index.js

✅ Closes: #225
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 Wrap window block in check

---

packages/falso/src/lib/credit-card.ts

Update category so it sits with other entities
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: 📘 Change creditCard category from entity to entities

---

packages/falso/src/lib/food.json

```
[ ] Bugfix
[x] Feature
```
Few typical foods in Colombia and Venezuela
New foods added in Colombia and venezuela
```
[ ] Yes
[x] No
```

feat: 🔥 New foods added in colombia and venezuela

---

packages/falso/src/lib/bic.ts
packages/falso/src/lib/iban.ts
packages/falso/src/lib/swift.ts
packages/falso/src/tests/account.spec.ts
packages/falso/src/tests/bic.spec.ts
packages/falso/src/tests/iban.spec.ts
packages/falso/src/tests/swift.spec.ts

```
[ ] Bugfix
[x] Feature
```
Added SWIFT / BIC code generation and minor changes to IBAN with test suite 
```
[ ] Yes
[X] No
```

SWIFT / BIC generation and IBAN minor changes

---

packages/falso/src/lib/uuid.ts
packages/falso/src/tests/uuid.spec.ts

✅ Closes: #232
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐞 Generate uuid from seed

---

package-lock.json
package.json
packages/falso/src/lib/core/core.ts
packages/falso/src/lib/rand.ts
packages/falso/src/tests/rand.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

support readonly arrays

---

README.md
docs/docs/getting-started.mdx
packages/falso/src/index.ts
packages/falso/src/lib/core/isNotNil.ts
packages/falso/src/lib/incremental-number.ts
packages/falso/src/tests/incremental-number.spec.ts

add randIncrementalNumber function
✅ Closes: #278
- [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
Issue Number: #278 
Generates an incremental number.
```
[ ] Yes
[x] No
```
Not really sure about the docs - running the build:docs task results in:
`no such file or directory, open 'packages\falso\src\index_packages\falso\src\lib\i18n\ar.ts'`
Feedback is appreciated. 
Thanks

feat: 🔥 add randIncrementalNumber function

---

docs/docs/factories.mdx
packages/falso/src/index.ts
packages/falso/src/lib/factories/incremental-date.ts
packages/falso/src/lib/factories/incremental-number.ts
packages/falso/src/tests/incremental-date.spec.ts

✅ Closes: #277
```
[ ] Bugfix
[x] Feature
```
Issue Number: #277
```
[ ] Yes
[x] No
```

feat: 🔥 add randIncrementalDate function

---

packages/falso/src/lib/account.ts
packages/falso/src/lib/amount.ts
packages/falso/src/lib/core/core.ts
packages/falso/src/tests/amount.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

randAmmount should return number by default

---

package-lock.json
package.json

closes #293 
```
[ ] Bugfix
[x] Feature
```
Issue Number: 293
```
[ ] Yes
[x] No
```

feat: add npm and node version info to package.json

---

packages/falso/src/lib/food.json
packages/falso/src/lib/food.ts

```
[ ] Bugfix
[x] Feature
```
Central America need more country options
Another LATAM country in option list
```
[ ] Yes
[x] No
```

feat: 🔥 Add more latam food

---

packages/falso/src/lib/paragraph.ts

randParagraph was not using the correct function in its examples.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: 📘 fix paragraph example

---

README.md
docs/docs/getting-started.mdx
packages/falso/src/index.ts
packages/falso/src/lib/motorcycle-manufacturer.json
packages/falso/src/lib/motorcycle-manufacturer.ts
packages/falso/src/tests/motorcylce-manufacturer.spec.ts

Add motorcycle manufacturers
```
[ ] Bugfix
[x] Feature
```
There is no motorcycle manufacturers, only vehicle manufacturers
There are motorcycle manufacturers
```
[ ] Yes
[x] No
```

feat: 🔥 Add motorcycle manufacturers

---

packages/falso/src/lib/core/core.ts
packages/falso/src/tests/get-random-in-range.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #307

fix(random): throw error when max is smaller than min

---

packages/falso/src/tests/incremental-number.spec.ts

when error case there are missing test codes so I implemented them!
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: missing test code
```
more safe code 
```
[ ] Yes
[x] No
```

test: 🥳 incremental-number missing test code

---

README.md
docs/docs/getting-started.mdx
packages/falso/src/index.ts
packages/falso/src/lib/abn.ts
packages/falso/src/lib/core/validators.ts
packages/falso/src/tests/abn.spec.ts

```
[ ] Bugfix
[x] Feature
```
N/A
Generates random valid Australian Business Numbers (ABN) based on the [validation rules](https://abr.business.gov.au/Help/AbnFormat) outlined by the government.
```
[ ] Yes
[X] No
```
Added a validator however not sure if that is the right place I put it.
Feels like that is reserved for more generic ones and I should move mine as part of the ABN ?

feat: added random Australian Business Number (ABN)

---

package-lock.json
package.json
packages/falso/project.json
packages/falso/rollup.config.js
packages/falso/src/tests/between-date.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Minify output

---

packages/falso/src/lib/book.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Fix randBook return type

---

README.md
docs/docs/getting-started.mdx
packages/falso/src/index.ts

```
[x] Bugfix
[ ] Feature
```
`randDatabase()` added with #322 can't be used because it's not exported.
`randDatabase()` is exported.
```
[ ] Yes
[x] No
```

fix: 🐞 export randDatabase()

---

packages/falso/src/lib/i18n/de/bird.i18n.json
packages/falso/src/lib/i18n/de/bird.ts
packages/falso/src/lib/i18n/de/index.ts
packages/falso/src/tests/bird.spec.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: i18n birds in german

---

README.md

Remove Fako because it's no longer maintained
My domain `microkit.co` expired and I did not renew it. Given the low number of visitors it's probably not worth to deploy and maintain the project on a new domain.

docs: 📘 remove fako

---

README.md

fixes #287
updates stackblitz link in readme.md file
- Issue Number: #287
updated stackblitz link

docs(stackblitz): update link with new version

---

packages/falso/src/lib/first-name.ts

Improve `names` variable operator readability.

refactor(randFirstName): 💡 improve names variable ternary operator readabilty

---

packages/falso/src/lib/core/core.ts
packages/falso/src/lib/sequence.ts
packages/falso/src/tests/sequence.spec.ts

fix(typing): randSequence

---

README.md

Show the contributors on readme to have more engagement with contributors.

doc: contributors list on readme

---

.github/workflows/ci.yml
.github/workflows/docs.yml

fix(ci): tune workflows

---

docs-generator.js

docs-generator.js returns no error yet an empty auto-generated folder

fix: docs-generator.js returns an empty auto-generated folder
