packages/falso/src/lib/rgb.ts, packages/falso/src/sketch.spec.ts, packages/falso/src/tests/rgb.spec.ts
Update rgb function to dynamically generate rgb strings rather than
picking one from predetermined list. Add basic unit tests for rgb
function.
✅ Closes: #4 
```
[ ] Bugfix
[x] Feature
```
The `rgb` function returns an RGB string from a static list.
Issue Number: 4
The `rgb` function generates and returns a dynamic RGB string
```
[ ] Yes
[x] No
```
=> feat: 🔥 update rgb() to return dynamically generated rgb string

CONTRIBUTING.md, tools/generators/falso/index.ts, tools/generators/falso/schema.json
```
[ ] Bugfix
[ ] Feature
```
The falso workspace generator did not :
- create a matching `.json` file for the newly to add falso
- declare function with `FakeOptions` parameter / type
The falso workspace generate will :
- generating a matchin falso JSON file according `--json` option value (default : `false`) 
- support `FakeOptions` to function definition
```
[ ] Yes
[x] No
```
=> refactor: 💡 Updated Falso generator to support JSON repo / FakeOption

packages/falso/src/lib/sentence.ts, packages/falso/src/tests/sentence.spec.ts
```
[x] Bugfix
[ ] Feature
```
If the word count is met, the loop is broken before full-stop is appended
Demonstrated in [this comment](https://github.com/ngneat/falso/pull/23#issuecomment-1013841367)
Check for word count when adding special character
```
[ ] Yes
[x] No
```
=> fix: 🐞 Ensure that fullstop is appended when wordCount is met

packages/falso/src/lib/protocol-full.json, packages/falso/src/lib/protocol.json, packages/falso/src/lib/protocol.ts, packages/falso/src/tests/protocol.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Extends the randProtocol method to return full names.
Issue Number: #86
```
[ ] Yes
[x] No
```
=> feat: extend randProtocol to return full names of protocols #86

packages/falso/src/lib/full-name.ts, packages/falso/src/tests/full-name.spec.ts
Fix issue where length value is passed to randFirstName and randLastName
meaning the formatting is broken
✅ Closes: #100
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: 🐞 Full name formatting when length is passed

README.md, packages/falso/src/index.ts, packages/falso/src/lib/octal.ts, packages/falso/src/tests/octal.spec.ts
Add generator for octal numbers limited to MAX_SAFE_INTEGER.
✅ Closes: #131
```
[ ] Bugfix
[X] Feature
```
Issue Number: #131 
Possibility of generating random octal numbers, with limited value (in decimal radix) to MAX_SAFE_INTEGER.
```
[ ] Yes
[X] No
```
=> feat: 🔥 add octal number generator

docs-generator.js, packages/falso/src/lib/address.ts, packages/falso/src/lib/email.ts, packages/falso/src/lib/post.ts, packages/falso/src/lib/superhero.ts, packages/falso/src/lib/user.ts
Add multi category logic. Update functions with to have multiple
categories
✅ Closes: #175
```
[ ] Bugfix
[x] Feature
```
Issue Number: 175
```
[ ] Yes
[x] No
```
=> docs: 📘 Added option to add functions to multiple categories

packages/falso/src/lib/sports.json, packages/falso/src/tests/sports.spec.ts
Renamed the sports category in JSON from olympicWinter to winterOlympic
to match the type definition
✅ Closes: #201
```
[x] Bugfix
[ ] Feature
```
Issue Number: 201
```
[ ] Yes
[x] No *
```
\* It's not a breaking change for TS users. If someone uses JS (or `any`) and relies on `olympicWinter` it's a breaking change.
I added a test for the fixed category though I'm not sure if that is correct (let me know if not).
=> fix: 🐞 sports category olympicWinter in JSON

packages/falso/src/lib/airport.ts, packages/falso/src/lib/flight-details.ts, packages/falso/src/lib/flight-number.ts, packages/falso/src/lib/text-range.ts, packages/falso/src/tests/flight-number.spec.ts
- Refactor multiple flight number generators into 1 more generic one and add more airlines to switch statement
-Remove return types from Falso functions as they were stopping the typing from automatically working without casting. Add missing documentation
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat: 🔥 Add more flight number generators for various airlines

docs/docusaurus.config.js, docs/src/consolePlayground/index.js
Add falso.min to window._ so users can try it out from the docs site
https://user-images.githubusercontent.com/7142779/159265162-01a8e5a9-af9b-4692-9aba-ddd92211a21e.mp4
✅ Closes: #225
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat: 🔥 Allow users to access falso on doc site console

packages/falso/src/lib/float.ts, packages/falso/src/lib/number.ts, packages/falso/src/tests/number.spec.ts, packages/falso/src/tests/random-float.spec.ts
```
[ ] Bugfix
[x] Feature
```
Cannot specify precision of randNumber
Issue Number: #226 
to be able to round numbers to closest 10, 100, 1000 you can set the precision of randNumber
```
[ ] Yes
[x] No
```
I hope it conforms to all the coding rules.
:)
=> feat: add precision to randNumber

packages/falso/src/lib/core/core.ts, packages/falso/src/tests/rand.spec.ts
The fix ensures when the user provides a length the helper returns
always an array.
BREAKING CHANGE: 🧨 Setting the option length 0 returns now an array
✅ Closes: #253
```
[x] Bugfix
[ ] Feature
```
Issue Number: #253 
```
[x] Yes
[ ] No
```
Calling an helper without the option `length` used to produce the same result as calling it with `0`. Now, setting the `length` to `0` returns an array.
=> fix: 🐞 Return an empty array when length is 0

packages/falso/src/lib/git-commit-sha.ts, packages/falso/src/lib/git-short-sha.ts
Seen an error in docs, git commit hash contains only hexa-decimals, but in docs it was any alphanumeric value.
Fixed it
=> Fix randGitShortSha and randGitCommitSha

packages/falso/src/lib/hexa-decimal.ts
Fix Probability distribution to uniform distribution
Previously, the chance of any random letter and any digit was equal, but the chance of a specific number was 1/(2*10) = 5% and the chance of a specific letter was 1/2/16 = 8.(3)%
Now the chance of a specific number and a specific letter are equals.
=> Fix Probability distribution

jest.preset.js, packages/falso/src/lib/core/core.ts, packages/falso/src/lib/sequence.ts, packages/falso/src/tests/random-float.spec.ts, packages/falso/src/tests/sequence.spec.ts
```
[ ] Bugfix
[X] Feature
[X] Other... Please describe:
```
fix flaky test check for `random-float`
`randSequence` can generate sequence via predefined char patterns:
- `alpha` [Aa-Zz] 
- `numeric` [0-9]  
- `alphaNumeric` [Aa-Zz0-9]
```
[ ] Yes
[X] No
```
=> randSequence with charsType pattern

README.md, docs/docs/getting-started.mdx, packages/falso/src/index.ts, packages/falso/src/lib/amount.ts, packages/falso/src/lib/float.ts, packages/falso/src/tests/amount.spec.ts, packages/falso/src/tests/float.spec.ts
generate random amount with possibility to use currency symbol with
amount
```
[ ] Bugfix
[X] Feature
```
introduce `randAmount` it's just `randFloat` but under the `@finance` domain and have type `string` and with possibility to set currency symbol
```
[ ] Yes
[X] No
```
=> feat: 🔥 introduce randAmount

packages/falso/src/tests/full-name.spec.ts
Update regex to handle tripple barrel surnames. Fix copy & paste errors
in tests.
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: 🐞 Fix full name tests

packages/falso/src/lib/between-date.ts, packages/falso/src/tests/between-date.spec.ts, packages/falso/src/tests/dates.spec.ts
Allow date strings for betweenDate
```
[ ] Bugfix
[x] Feature
```
`betweenDate` only allows Date objects
`betweenDate` now accepts strings as well, which then is converted to Dates automatically
```
[ ] Yes
[x] No
```
=> feat: 🔥 allow date strings for betweenDate

packages/falso/src/lib/last-name.json, packages/falso/src/tests/first-name.spec.ts, packages/falso/src/tests/last-name.spec.ts
```
[x] Bugfix
[ ] Feature
```
🐞  There is an unexpected accent that appears in the last names **without** accents.
* Remove the unexpected character, `ą`
```
[ ] Yes
[x] No
```
There is a spec that we would have expected to catch this. I've added a new test case to confirm the names without accents do not contain unexpected characters. You may have to update the character group as you add names, such as adding the `'` for `O'Reilly`.
=> fix: Remove unexpected accent from names without accents

packages/falso/src/lib/company-name.json
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
It removes a company that stood in a presentation.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[x] No
```
I know it's a bit difficult, it's a real company it seems but still...
I understand if the PR gets rejected :)
=> Remove gaylord company

packages/falso/src/lib/uuid.ts, packages/falso/src/tests/uuid.spec.ts
randUuid generated a random id and saved it in a constant that was used multiple times
✅ Closes: 313
```
[x] Bugfix
[ ] Feature
```
randUuid returns the same id multiple times with the length parameter #313
Issue Number: 313
randUuid returns different ids with the length parameter
```
[ ] Yes
[x ] No
```
=> fix: 🐞 randUuid returns the same id multiple times with length parameter

docs/docusaurus.config.js, docs/src/pages/index.js
wrote link is inserted before which indicate elf repository
change wrong link in docs
```
[ ] Bugfix
[ ] Feature
```
docs link indicate falso repository not elf repository
```
[ ] Yes
[x] No
```
=> docs: 📘 change elf link to falso link for docusarous

packages/falso/src/lib/database.json, packages/falso/src/lib/database.ts, packages/falso/src/tests/database.spec.ts
When I want database name I can use this function
```
[ ] Bugfix
[x] Feature
```
developer can use this function to make random database 
```
[ ] Yes
[x] No
```
=> feat: 🔥 randDatabase which create database top25

packages/falso/src/lib/float.ts
When I insert fraction 3 It can return 15 15.3 15.32 15.323 
Developers who want to get a three-digit decimal point will surely expect a three-digit decimal point. They don't want a two-digit, one-digit decimal point. Therefore, it is necessary to return a value with an accurate decimal point that fits the fractions.
```
[x] Bugfix
[ ] Feature
```
every time randFloat is called It strictly return fractional value
Issue Number: this problem found …
=> fix: 🐞 randFloat sometime didn't adhere fraction strictly

docs/docusaurus.config.js
change /false => /falso which I made ..
I'm sorry. I'll make sure to check next time!
```
[ ] Bugfix
[ ] Feature
```
when click github logo in docs people can go this repository
```
[ ] Yes
[x] No
```
=> docs: 📘 change wrong path in docs

packages/falso/src/lib/aws-service.json, packages/falso/src/tests/aws-service.spec.ts
Service name "Cognito" was duplicated in aws-service.json so I remove one and there isn't test code which verify aws-service function so I wrote it
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat: 🔥 write aws-service test code & remove duplicated service

package-lock.json, packages/falso/src/lib/food.ts, packages/falso/src/lib/sports.ts, packages/falso/src/lib/utils/objectKeys.ts
I made objectKeys which can infer type strictly by behaving identical like Object.keys() function.
```
[ ] Bugfix
[ ] Feature
```
In the original code, when data was added in json file, two file had to be modified, but through type inference, even if data is added, only one place(json file) needs to be modified. This increased the ease of maintenance.
reponed by #324 because of git issue😂
same as before but increased the ease of maintenance.
```
[ ] …
```
=> refactor: 💡 more type enhancement using built-in keyword

packages/falso/src/tests/get-random-in-range.spec.ts
I have verified that the value returned by getRandomInRange may be equal to the min value
I tried to modify `getRandomInRange` to return a value greater than the min value always, but I did not modify the function because the developer might think that the return value also contains a min value(can be equal).
Which do you prefer, fixing the test code or modifying the function?
```
[x] Bugfix
[ ] Feature
```
test code always pass all test
```
[ ] Yes …
```
=> test: 🥳 getRandomInRange can return same value as min value

packages/falso/src/lib/img.ts
The function randImg() returns a URL string using [placeimg.com](https://placeimg.com/), but the service will be shutting down on June 23rd, 2023
The function randImg() now returns a URL string using [Lorem Picsum](https://picsum.photos/).
This service doesn't support the "category" option, so I removed it.
The service supports other options, I implemented a "grayscale" boolean option.
And last, I changed the default behaviour for "width" and "height" options: now if either of the two options is provided, it return a square image (setting the non-set option equal to the set one).
Unfortunately the "category" option is not supported by the new service. It will not …
=> fix: change random image service

packages/falso/src/lib/float.ts, packages/falso/src/tests/float.spec.ts
✅ Closes: #354
`randFloat` produces stack overflow if `min` and `max` are integers and equal:
- Issue Number: #354
- Resolve #354
The underlying issue is that the `randFloat` `factory` refuses to return a number that has fewer than `options.fraction` digits after the decimal point. There is no number between 0 and 0 that has a (required) digit after the decimal place, so the function infinitely recursed.
Moreover, it is very surprising behavior that `randFloat({ min: 0, max: 1, fraction: 2 })` will NEVER return the numbers 0, 0.1, 0.2, ..., 0.9, or 1. If this is expected behavior, it needs to be clearly documented because it likely different from how the user would expect the …
=> fix: 🐞 Fix `randFloat` infinite recursion and logical issue

packages/falso/src/lib/user-name.ts, packages/falso/src/tests/user-name.spec.ts
`randUserName()` generates random user names including those with accented characters (e.g: `Jiángüo.Karlsdóttir36`)
with the option: `withAccents: boolean` we can control if the function should generate user names with accents or not
```ts
randUserName({withAccents: false}) // Rattana.Harrison78
randUserName({withAccents: true}) // Dilóp.Háràldsdóttir93
```
=> add withAccents option to randUserName()

README.md, packages/falso/src/lib/core/core.ts, packages/falso/src/lib/utils/validators.utils.ts, packages/falso/src/tests/max-char-count.spec.ts, packages/falso/src/tests/movie.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #299
=> feat(size): allow to specify string length of random values

tools/executors/build-locales/index.ts
"main": "./index.cjs.js" fixed for all i18n for "main": "./index.cjs"
✅ Closes: 363
- Issue Number: 363
- Resolve #363
=> fix: 🐞 i18n package.json files fixed

packages/falso/src/lib/img.ts
Previously, the resulting image would be cached by the browser. So, when using `randImg()` on a set of components like React or Solid, the images between components will be the same. I just added the `random` option as described at https://picsum.photos in the Advanced Usage section.
The option `random` should be enabled as it would commonly used in this situation.
=> feat(img): allow generating random image by default

docs-generator.js
doc generator script returns error after sequence.ts update. The problem possibly, it is trying to update the related docs to that update file but no category found.
=> fix: doc generator script returns error

packages/falso/src/lib/sequence.ts, packages/falso/src/tests/sequence.spec.ts
=> fix: broken sequence

packages/falso/src/lib/sequence.ts, packages/falso/src/tests/password.spec.ts
=> fix: wrong returned type

packages/falso/src/lib/img.ts, packages/falso/src/tests/product.spec.ts
=> fix: broken randImg

packages/falso/src/lib/collection.ts, packages/falso/src/tests/collection.spec.ts
=> type with {length: number} instead of never
